---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.fullnameOverride }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubesage.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.postgresql.password | quote }}
  postgres-password: {{ .Values.postgresql.postgresPassword | quote }}
