---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubesage.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubesage.fullname" . }}
  namespace: {{ include "kubesage.fullname" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "kubesage.fullname" . }}
  apiGroup:
    rbac.authorization.k8s.io