---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubesage-config
  namespace: kubesage
data:
  ENVIRONMENT: "development"
  LOG_LEVEL: "INFO"
  PROMETHEUS_URL: "http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090"
  OPENAI_URL: "http://host.minikube.internal:11434/v1"
  OPENAI_MODEL: "qwen2.5-coder:14b"
