---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubesage.fullname" . }}-config
data:
  DATABASE_HOST: {{ .Values.database.host | quote }}
  DATABASE_PORT: {{ .Values.database.port | quote }}
  DATABASE_NAME: {{ .Values.database.name | quote }}
  DATABASE_USER: {{ .Values.database.username | quote }}
  ENVIRONMENT: {{ .Values.application.environment | quote }}
  LOG_LEVEL: {{ .Values.application.logLevel | quote }}
  AI_MODEL: {{ .Values.ai.model | quote }}
  AI_URL: {{ .Values.ai.endpoint | quote }}
  AI_PROVIDER: {{ .Values.ai.provider | quote }}
  {{ if .Values.observability.prometheus.enabled }}
  PROMETHEUS_URL: {{ .Values.observability.prometheus.url | quote }}
  {{ end }}
  {{ if .Values.observability.loki.enabled }}
  LOKI_URL: {{ .Values.observability.loki.url | quote }}
  {{ end }}
  {{ if .Values.observability.tempo.enabled }}
  OTLP_ENDPOINT: {{ .Values.observability.tempo.url | quote }}
  {{ end }}
