{{- if .Values.observability.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "kubesage.fullname" . }}
spec:
  groups:
  - name: {{ include "kubesage.fullname" . }}
    rules:
    - alert: KubeSageDown
      expr: up{job="{{ include "kubesage.fullname" . }}"} == 0
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "KubeSage is unreachable"
{{- end }}