"""add pod_ui

Revision ID: 0057b6bfd9fb
Revises: 4fae00c17465
Create Date: 2026-08-27 18:29:58.676849

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0057b6bfd9fb"
down_revision: str | Sequence[str] | None = "4fae00c17465"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analyses", sa.Column("pod_uid", sa.String(length=255), nullable=True)
    )
    op.create_index(op.f("ix_analyses_pod_uid"), "analyses", ["pod_uid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_analyses_pod_uid"), table_name="analyses")
    op.drop_column("analyses", "pod_uid")
    # ### end Alembic commands ###
