"""add additionnal fields for IA report

Revision ID: 0e98dd58fd70
Revises: 0057b6bfd9fb
Create Date: 2026-09-01 19:30:34.253874

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0e98dd58fd70"
down_revision: str | Sequence[str] | None = "0057b6bfd9fb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis_correlations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("analysis_id", sa.String(), nullable=False),
        sa.Column("source_finding", sa.String(length=255), nullable=False),
        sa.Column("target_finding", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analyses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analysis_correlations_analysis_id"),
        "analysis_correlations",
        ["analysis_id"],
        unique=False,
    )
    op.create_table(
        "analysis_root_causes",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("analysis_id", sa.String(), nullable=False),
        sa.Column("finding", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("supporting_findings", sa.Text(), nullable=True),
        sa.Column("supporting_evidence", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["analysis_id"],
            ["analyses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analysis_root_causes_analysis_id"),
        "analysis_root_causes",
        ["analysis_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_analysis_root_causes_analysis_id"), table_name="analysis_root_causes"
    )
    op.drop_table("analysis_root_causes")
    op.drop_index(
        op.f("ix_analysis_correlations_analysis_id"), table_name="analysis_correlations"
    )
    op.drop_table("analysis_correlations")
    # ### end Alembic commands ###
