"""add resources to findings

Revision ID: 4fae00c17465
Revises: c49a5a873ec6
Create Date: 2026-08-19 17:53:18.301038

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "4fae00c17465"
down_revision: str | Sequence[str] | None = "c49a5a873ec6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ai_reports",
        "additional_investigations",
        existing_type=sqlite.JSON(),
        nullable=False,
    )
    op.add_column(
        "findings",
        sa.Column("resource_api_version", sa.String(length=100), nullable=True),
    )
    op.add_column(
        "findings", sa.Column("resource_kind", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "findings",
        sa.Column("resource_namespace", sa.String(length=255), nullable=True),
    )
    op.add_column(
        "findings", sa.Column("resource_name", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("findings", "resource_name")
    op.drop_column("findings", "resource_namespace")
    op.drop_column("findings", "resource_kind")
    op.drop_column("findings", "resource_api_version")
    op.alter_column(
        "ai_reports",
        "additional_investigations",
        existing_type=sqlite.JSON(),
        nullable=True,
    )
    # ### end Alembic commands ###
