"""add trace_id to analysis

Revision ID: 63c330af54f0
Revises: 0e98dd58fd70
Create Date: 2026-09-02 21:19:38.772610

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "63c330af54f0"
down_revision: str | Sequence[str] | None = "0e98dd58fd70"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analyses", sa.Column("trace_id", sa.String(length=32), nullable=True)
    )
    op.create_index(
        op.f("ix_analyses_trace_id"), "analyses", ["trace_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_analyses_trace_id"), table_name="analyses")
    op.drop_column("analyses", "trace_id")
    # ### end Alembic commands ###
