"""add findings_count and indexes

Revision ID: 9fd46207aec7
Revises: 9486b865b425
Create Date: 2026-08-04 11:19:36.332084

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9fd46207aec7"
down_revision: str | Sequence[str] | None = "9486b865b425"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("analyses", sa.Column("findings_count", sa.Integer(), nullable=False))
    op.create_index("ix_analysis_created_at", "analyses", ["created_at"], unique=False)
    op.create_index(
        "ix_analysis_highest_severity", "analyses", ["highest_severity"], unique=False
    )
    op.create_index("ix_analysis_namespace", "analyses", ["namespace"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_analysis_namespace", table_name="analyses")
    op.drop_index("ix_analysis_highest_severity", table_name="analyses")
    op.drop_index("ix_analysis_created_at", table_name="analyses")
    op.drop_column("analyses", "findings_count")
    # ### end Alembic commands ###
