"""add additionnal fields for IA report

Revision ID: c49a5a873ec6
Revises: cacb3b13490f
Create Date: 2026-08-06 20:33:29.537753

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c49a5a873ec6"
down_revision: str | Sequence[str] | None = "cacb3b13490f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ai_reports", sa.Column("confidence", sa.Float(), nullable=True))
    op.add_column("ai_reports", sa.Column("impact", sa.Text(), nullable=True))
    op.add_column(
        "ai_reports", sa.Column("additional_investigations", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ai_reports", "additional_investigations")
    op.drop_column("ai_reports", "impact")
    op.drop_column("ai_reports", "confidence")
    # ### end Alembic commands ###
