"""Add trigger field to analysis

Revision ID: cacb3b13490f
Revises: 9fd46207aec7
Create Date: 2026-08-06 16:44:49.546497

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cacb3b13490f"
down_revision: str | Sequence[str] | None = "9fd46207aec7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analyses", sa.Column("trigger", sa.String(length=25), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("analyses", "trigger")
    # ### end Alembic commands ###
