---
apiVersion: v1
kind: Pod
metadata:
  name: kubesage-cpu-throttling
  namespace: default
spec:
  containers:
    - name: cpu
      image: progrium/stress
      args:
        - "--cpu"
        - "2"
      resources:
        requests:
          cpu: 100m
        limits:
          cpu: 100m