---
apiVersion: v1
kind: Pod
metadata:
  name: kubesage-error-logs
  namespace: default
spec:
  restartPolicy: Never
  containers:
    - name: logger
      image: busybox
      command:
        - sh
        - -c
        - |
          echo "ERROR Database connection refused"
          echo "Exception: timeout"
          sleep 600
