---
apiVersion: v1
kind: Pod
metadata:
  name: kubesage-high-cpu
  namespace: default
spec:
  containers:
    - name: cpu
      image: nickborgers/stress:v1.5.1
      command:
        - stress
      args:
        - "--cpu"
        - "2"
      resources:
        limits:
          cpu: 0.5