---
apiVersion: v1
kind: Pod
metadata:
  name: kubesage-oom
  namespace: default
spec:
  containers:
    - name: stress
      image: polinux/stress
      resources:
        limits:
          memory: 64Mi
      command:
        - stress
      args:
        - "--vm"
        - "1"
        - "--vm-bytes"
        - "256M"
        - "--vm-hang"
        - "1"
