---
apiVersion: v1
kind: Pod
metadata:
  name: kubesage-pending-pod
  namespace: default
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /data
          name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: pvc-does-not-exist
