---
apiVersion: v1
kind: Pod
metadata:
  name: kubesage-readiness-fail
  namespace: default
spec:
  containers:
    - name: nginx
      image: nginx
      readinessProbe:
        httpGet:
          path: /does-not-exist
          port: 80
