---
apiVersion: v2
name: kubesage
description: AI-powered Kubernetes incident assistant
type: application
version: 0.1.0
appVersion: "0.11.0"
icon:https://raw.githubusercontent.com/fdebar/kubesage/refs/heads/main/docs/kubesage-logo.png
