---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubesage.fullname" . }}-config
data:
  #TODO: fix the hardcoded password
  DATABASE_URL: postgresql+psycopg://{{ .Values.postgresql.auth.username }}:{{ .Values.postgresql.auth.password }}@{{ include "kubesage.fullname" . }}-postgresql:5432/{{ .Values.postgresql.auth.database }}
  ENVIRONMENT: {{ .Values.application.environment | quote }}
  LOG_LEVEL: {{ .Values.application.logLevel | quote }}
  AI_MODEL: {{ .Values.ai.model | quote }}
  AI_URL: {{ .Values.ai.endpoint | quote }}
  AI_PROVIDER: {{ .Values.ai.provider | quote }}
  {{ if .Values.observability.prometheus.enabled }}
  PROMETHEUS_URL: {{ .Values.observability.prometheus.url | quote }}
  {{ end }}
  {{ if .Values.observability.loki.enabled }}
  LOKI_URL: {{ .Values.observability.loki.url | quote }}
  {{ end }}
  {{ if .Values.observability.tempo.enabled }}
  OTLP_ENDPOINT: {{ .Values.observability.tempo.url | quote }}
  {{ end }}
