---
apiVersion: v1
kind: Secret
metadata:
  name:  {{ include "kubesage.fullname" . }}-secret
type: Opaque
stringData:
  DATABASE_PASSWORD: {{ .Values.postgresql.auth.password | default "" | quote }}
  AI_API_KEY: {{ .Values.ai.apiKey | default "" | quote }}
