{{- if .Values.api.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kubesage.fullname" . }}-api
  namespace: monitoring
  labels:
    {{- include "kubesage.labels" . | nindent 4 }}
    {{- if .Values.api.metrics.additionalLabels }}
      {{- toYaml .Values.api.metrics.additionalLabels | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - kubesage
  selector:
    matchLabels:
      {{- include "kubesage.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
{{- end }}
