import re

from pydantic import BaseModel, Field, field_validator


class AIReport(BaseModel):
    """
    Structured report generated by the AI analysis.
    """

    summary: str = Field(description="Short summary of the incident.")
    root_cause: str | None = Field(
        default=None,
        description="Most likely root cause of the incident.",
    )
    confidence: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Confidence score between 0 and 1.",
    )
    impact: str | None = Field(
        default=None,
        description="User or system impact caused by the incident.",
    )
    findings: list[FindingReference] = Field(
        default_factory=list,
        description="Findings supporting the analysis.",
    )
    evidence: list[EvidenceReference] = Field(
        default_factory=list,
        description="Evidence references supporting the analysis.",
    )
    recommendations: list[str] = Field(
        default_factory=list,
        description="Recommended remediation actions.",
    )
    additional_investigations: list[str] = Field(
        default_factory=list,
        description="Additional checks suggested by the AI.",
    )


class FindingReference(BaseModel):
    """
    Stable reference to a Finding used by the AI analysis.
    """

    rule: str
    description: str | None = None


class EvidenceReference(BaseModel):
    """
    Stable identifier of a piece of evidence.
    Generated using the Evidence.id property.
    """

    id: str
    description: str | None = None
    source: str | None = None

    @field_validator("id", mode="before")
    @classmethod
    def normalize_id(cls, value: object) -> object:
        """
        Normalize common formatting artifacts produced by LLMs.

        Evidence IDs are opaque identifiers generated by KubeSage.
        The model must return them exactly, but some local LLMs can
        occasionally prefix/suffix an identifier with punctuation.

        This validator only removes surrounding formatting characters.
        It does not invent, transform, or otherwise derive an ID.
        """

        if not isinstance(value, str):
            return value

        normalized = value.strip()

        # Remove common Markdown / JSON formatting artifacts around IDs.
        normalized = normalized.strip("`'\"")

        # Evidence IDs currently use lowercase hexadecimal characters.
        # Only remove punctuation when it is clearly outside the identifier.
        normalized = re.sub(r"^[^a-zA-Z0-9]+", "", normalized)
        normalized = re.sub(r"[^a-zA-Z0-9]+$", "", normalized)

        return normalized
