apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubesage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fdebar/kubesage.git
    targetRevision: main
    path: ./charts/kubesage
    helm:
      valueFiles:
        - ../../charts/kubesage/values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kubesage
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
