name: Kubesage Helm Chart
on:
  push:
    branches: [ main ]
    paths:
      - "charts/**"
  pull_request:
    branches: [ main ]
    paths:
      - "charts/**"
  workflow_dispatch:

jobs:
  helm-test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Helm
        uses: azure/setup-helm@v5

      - name: Lint Helm chart
        run: make helm-lint

      - name: Build Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: false
          tags: |
            kubesage:helm-test

      - name: Create Kind cluster
        uses: helm/kind-action@v1.14.0
        with:
          cluster_name: kind-kubesage

      - name: Load Docker image into Kind
        run: |
          kind load docker-image kubesage:helm-test --name kind-kubesage

      - name: Deploy Helm chart
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add postgresql https://charts.bitnami.com/bitnami
          helm repo update
          helm upgrade --install prometheus prometheus-community/kube-prometheus-stack -n monitoring --create-namespace

          helm dependency build charts/kubesage
          helm upgrade --install kubesage ./charts/kubesage \
            --namespace kubesage \
            --create-namespace \
            --set api.image.repository=kubesage \
            --set api.image.tag=helm-test \
            --set ai.apiKey=ollama

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/kubesage-api \
            -n kubesage \
            --timeout=360s

      - name: Dump Logs if Failed
        if: failure()
        run: |
          kubectl get pods -n kubesage
          kubectl describe deployment/kubesage-api -n kubesage
          kubectl logs deployment/kubesage-api -n kubesage --previous

  publish:
    needs: helm-test-and-deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Helm
        uses: azure/setup-helm@v5

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Package and Push
        run: |
          helm repo add postgresql https://charts.bitnami.com/bitnami
          helm repo update
          helm dependency build ./charts/kubesage
          helm package ./charts/kubesage -d dist/
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          helm push dist/kubesage-*.tgz oci://ghcr.io/$OWNER/charts
